// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: project/v1/problem/problem.proto

package problemv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Problem_CreateProblem_FullMethodName  = "/project.v1.problem.Problem/CreateProblem"
	Problem_DeleteProblem_FullMethodName  = "/project.v1.problem.Problem/DeleteProblem"
	Problem_UpdateProblem_FullMethodName  = "/project.v1.problem.Problem/UpdateProblem"
	Problem_GetProblemList_FullMethodName = "/project.v1.problem.Problem/GetProblemList"
)

// ProblemClient is the client API for Problem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProblemClient interface {
	// 题目管理
	CreateProblem(ctx context.Context, in *CreateProblemReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteProblem(ctx context.Context, in *DeleteProblemReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateProblem(ctx context.Context, in *UpdateProblemReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetProblemList(ctx context.Context, in *GetProblemListReq, opts ...grpc.CallOption) (*GetProblemListResp, error)
}

type problemClient struct {
	cc grpc.ClientConnInterface
}

func NewProblemClient(cc grpc.ClientConnInterface) ProblemClient {
	return &problemClient{cc}
}

func (c *problemClient) CreateProblem(ctx context.Context, in *CreateProblemReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Problem_CreateProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) DeleteProblem(ctx context.Context, in *DeleteProblemReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Problem_DeleteProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) UpdateProblem(ctx context.Context, in *UpdateProblemReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Problem_UpdateProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) GetProblemList(ctx context.Context, in *GetProblemListReq, opts ...grpc.CallOption) (*GetProblemListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProblemListResp)
	err := c.cc.Invoke(ctx, Problem_GetProblemList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProblemServer is the server API for Problem service.
// All implementations must embed UnimplementedProblemServer
// for forward compatibility.
type ProblemServer interface {
	// 题目管理
	CreateProblem(context.Context, *CreateProblemReq) (*emptypb.Empty, error)
	DeleteProblem(context.Context, *DeleteProblemReq) (*emptypb.Empty, error)
	UpdateProblem(context.Context, *UpdateProblemReq) (*emptypb.Empty, error)
	GetProblemList(context.Context, *GetProblemListReq) (*GetProblemListResp, error)
	mustEmbedUnimplementedProblemServer()
}

// UnimplementedProblemServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProblemServer struct{}

func (UnimplementedProblemServer) CreateProblem(context.Context, *CreateProblemReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProblem not implemented")
}
func (UnimplementedProblemServer) DeleteProblem(context.Context, *DeleteProblemReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProblem not implemented")
}
func (UnimplementedProblemServer) UpdateProblem(context.Context, *UpdateProblemReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProblem not implemented")
}
func (UnimplementedProblemServer) GetProblemList(context.Context, *GetProblemListReq) (*GetProblemListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProblemList not implemented")
}
func (UnimplementedProblemServer) mustEmbedUnimplementedProblemServer() {}
func (UnimplementedProblemServer) testEmbeddedByValue()                 {}

// UnsafeProblemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProblemServer will
// result in compilation errors.
type UnsafeProblemServer interface {
	mustEmbedUnimplementedProblemServer()
}

func RegisterProblemServer(s grpc.ServiceRegistrar, srv ProblemServer) {
	// If the following call pancis, it indicates UnimplementedProblemServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Problem_ServiceDesc, srv)
}

func _Problem_CreateProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProblemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).CreateProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_CreateProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).CreateProblem(ctx, req.(*CreateProblemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_DeleteProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProblemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).DeleteProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_DeleteProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).DeleteProblem(ctx, req.(*DeleteProblemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_UpdateProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProblemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).UpdateProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_UpdateProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).UpdateProblem(ctx, req.(*UpdateProblemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_GetProblemList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProblemListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).GetProblemList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_GetProblemList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).GetProblemList(ctx, req.(*GetProblemListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Problem_ServiceDesc is the grpc.ServiceDesc for Problem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Problem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "project.v1.problem.Problem",
	HandlerType: (*ProblemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProblem",
			Handler:    _Problem_CreateProblem_Handler,
		},
		{
			MethodName: "DeleteProblem",
			Handler:    _Problem_DeleteProblem_Handler,
		},
		{
			MethodName: "UpdateProblem",
			Handler:    _Problem_UpdateProblem_Handler,
		},
		{
			MethodName: "GetProblemList",
			Handler:    _Problem_GetProblemList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "project/v1/problem/problem.proto",
}
