// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameKnowledge = "knowledge"

// Knowledge mapped from table <knowledge>
type Knowledge struct {
	ID          int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name        string         `gorm:"column:name;type:varchar(255);not null;comment:知识点名称" json:"name"`                                    // 知识点名称
	Description string         `gorm:"column:description;type:text;comment:知识点描述" json:"description"`                                       // 知识点描述
	ParentID    int64          `gorm:"column:parent_id;type:bigint;index:parent_id,priority:1;comment:父知识点 ID，用于构建知识点树结构" json:"parent_id"` // 父知识点 ID，用于构建知识点树结构
	CreateTime  time.Time      `gorm:"column:create_time;type:datetime;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`          // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`  // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:删除时间，用于软删除" json:"deleted_at"`                               // 删除时间，用于软删除
}

// TableName Knowledge's table name
func (*Knowledge) TableName() string {
	return TableNameKnowledge
}
