// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID           int64  `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	Username     string `gorm:"column:username;type:varchar(50);not null;uniqueIndex:username,priority:1" json:"username"`
	PasswordHash string `gorm:"column:password_hash;type:varchar(255);not null" json:"password_hash"`
	IsAdmin      bool   `gorm:"column:is_admin;type:tinyint(1);not null" json:"is_admin"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
