server:
  http:
    addr: 0.0.0.0:8001
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 10s
log:
  stdout: true  # control output log to stdout
  path: ./log/
  max_size: 256
  max_age: 7
  max_count: 5
data:
  mysql:
    log_level: 4  # 1: silent, 2: error, 3: warn, 4: info, 5: debug
    host: 127.0.0.1
    port: "3306"
    user: root
    password: "123456"
    database: project_user
    max_idle: 10
    max_open: 100
  redis:
    host: 127.0.0.1
    port: "6379"
    db: 1
    password:
    dial_timeout: 1s
    read_timeout: 1s
    write_timeout: 1s
jwt:
  secret: Kth1utMBj4jXXVUgz5NtH8SGBnBLMYz
  access_token_expiration: 2                    #2 hours
#  refresh_token_expiration: 15                  #15 days