// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameExamPaper = "exam_paper"

// ExamPaper mapped from table <exam_paper>
type ExamPaper struct {
	ID         int64          `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Title      string         `gorm:"column:title;type:varchar(255);not null;comment:试卷标题" json:"title"`                                     // 试卷标题
	Questions  string         `gorm:"column:questions;type:json;not null;comment:题目列表（格式：[{"type":"choice","id":1}, ...]）" json:"questions"` // 题目列表（格式：[{"type":"choice","id":1}, ...]）
	CreateTime time.Time      `gorm:"column:create_time;type:datetime;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"deleted_at"`
}

// TableName ExamPaper's table name
func (*ExamPaper) TableName() string {
	return TableNameExamPaper
}
