// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQuestionChoice = "question_choice"

// QuestionChoice mapped from table <question_choice>
type QuestionChoice struct {
	ID      int64  `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	OptionA string `gorm:"column:option_a;type:text;not null" json:"option_a"`
	OptionB string `gorm:"column:option_b;type:text;not null" json:"option_b"`
	OptionC string `gorm:"column:option_c;type:text;not null" json:"option_c"`
	OptionD string `gorm:"column:option_d;type:text;not null" json:"option_d"`
	Answer  string `gorm:"column:answer;type:char(1);not null" json:"answer"`
}

// TableName QuestionChoice's table name
func (*QuestionChoice) TableName() string {
	return TableNameQuestionChoice
}
