// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQuestionJudge = "question_judge"

// QuestionJudge mapped from table <question_judge>
type QuestionJudge struct {
	ID     int64 `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	Answer int64 `gorm:"column:answer;type:tinyint(1);not null;comment:TRUE/FALSE" json:"answer"` // TRUE/FALSE
}

// TableName QuestionJudge's table name
func (*QuestionJudge) TableName() string {
	return TableNameQuestionJudge
}
