// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQuestionEssay = "question_essay"

// QuestionEssay mapped from table <question_essay>
type QuestionEssay struct {
	ID        int64  `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	Reference string `gorm:"column:reference;type:text;not null;comment:参考答案" json:"reference"` // 参考答案
}

// TableName QuestionEssay's table name
func (*QuestionEssay) TableName() string {
	return TableNameQuestionEssay
}
